# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Parham Adiban
title: Master's in Geophysics
email: parham.adiban@gmail.com
website: http://www.ete.inrs.ca/INRS-ETE

# Social links
# twitter_username: facespics
github_username:  adibanpa
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: padiban
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Parham and I'm a master's student at institut national de la recherche scientifique (INRS) in Quebec city.
  For my current project, I am looking at the statistical relationship between deep geological structures in western Superior 
  Province and gold deposits/showings.

  Quebec champion of the SEG challenge bowl 2019.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside geophysics, my other passions include:
   - Soccer
   - Gaming
   - Raquet sports
   - Fashion
   - Reducing my environmental footprint


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
